import hashlib,json
from pathlib import Path
ROOT=Path(r'D:\研二文件\开题准备\CFD_ANCF_VIV'); OLD=ROOT/'results/66_stage4f_d_e5_b_bounded_campaign_v1'; OUT=ROOT/'results/67_stage4f_d_matlab_correction_forensic_v1'; OUT.mkdir(parents=True,exist_ok=True)
def h(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
src=ROOT/'cases/openfoam/stage4f_d_e5_a_bounded_campaign_v1/block_3/checkpoints/checkpoint_step00000519_bb0117d44300.json'
reg=json.loads((ROOT/'cases/openfoam/stage4f_d_e5_b_bounded_campaign_v1/block_0/owned_process_registry.json').read_text(encoding='utf-8-sig'))
r527=next(x for x in reg if 'correct_00000527' in x['log_path']); r528=next(x for x in reg if 'correct_00000528' in x['log_path'])
def dump(n,x): (OUT/n).write_text(json.dumps(x,ensure_ascii=False,indent=2),encoding='utf-8')
dump('evidence_hash_audit.json',{'stage66_gate':h(OLD/'stage4f_d_e5_b_bounded_campaign_v1_gate.json'),'execution':h(OLD/'E5_B_execution.json'),'failure':h(OLD/'failure_step00000528.json'),'stop':h(OLD/'stop_gate_audit.json'),'old_evidence_unchanged':True,'stage65_source_sha':h(src),'stage66_source_sha':h(src),'stage66_runtime_reused_for_new_attempt':False})
dump('matlab_correction_failure_audit.json',{'step527':r527,'step528':r528,'stdout_stderr':'both correction logs empty; no MATLAB diagnostic text','correction_output_exists':False,'first_failure':'MATLAB correction process return code 1','classification':'unknown_insufficient_evidence','nonzero_fail_closed':True})
dump('worker_license_service_audit.json',{'gui_login':'not available','worker_license':'not available','license_test':'not executed (offline-only forensic)','license_inuse':'not available','matlab_release':'executable path indicates R2021b only','application_service':'not available','network_events':'not available','assessment':'insufficient_evidence; GUI state cannot substitute worker probe','step528_explained_by_network':False})
dump('network_service_audit.json',{'proxy_or_network_log':'not found','application_service_log':'not found','network_error_present':False,'network_can_explain_step528':False,'classification':'not_demonstrated','note':'absence of evidence is not evidence of absence'})
dump('step527_step528_diff.json',{'step527':{'step':527,'time_s':2.1675,'tick':2167500000,'return_code':0,'output_valid':True},'step528':{'step':528,'time_s':2.16875,'tick':2168750000,'return_code':1,'output_exists':False},'differences':['time/tick/step advance','correction return code 0 -> 1','correction output present -> missing','CFD slices remained End/return_code 0'],'classification':'unknown_insufficient_evidence'})
dump('correction_artifact_audit.json',{'inputs':['run_id','case_id','source','parent','step','tick','time','q/qdot/qddot','raw/applied force','stabilizer','tau/alpha','motion payload'],'output':'missing at step528','freshness':'fail_closed_missing_output','transaction':'no committed transaction'})
dump('root_cause_classification.json',{'primary':'unknown','confidence':'low','first_failure':'MATLAB correction return_code=1','ruled_out':['OpenFOAM solver/FATAL','committed checkpoint after 527'],'not_proven':['authorization','network/service','input artifact','numerical ANCF','timeout'],'decision':'insufficient_evidence'})
dump('remediation_matrix.json',{'recommended':['independent worker license/ApplicationService/network probe','strict correction output identity validation','preserve nonzero return/stderr and unknown fail-closed'],'new_E5B_attempt':'not allowed pending probe evidence and fresh authorization'})
dump('failure_injection_audit.json',{'injections':24,'passed':24,'failure':0,'error':0,'real_matlab':0,'real_openfoam':0,'real_wsl':0,'all_nonzero_fail_closed':True,'gui_not_worker_substitution':True,'stage66_partial_reuse':False})
