from __future__ import annotations
import json,hashlib,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]; OUT=ROOT/'results/51_stage4f_d_e3_entry_review_v1'; SRC=ROOT/'cases/openfoam/stage4f_d_e1_bounded_pilot_v1/block_3/checkpoints/checkpoint_step00000079_e19d01431943.json'; E2=ROOT/'results/50_stage4f_d_e2_bounded_pilot_v2/E2_execution.json'
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def build():
 e=json.loads(E2.read_text(encoding='utf-8')); per=e['wall_clock_s']/80; disk=e['disk_bytes']/80; src={'path':str(SRC),'id':'step00000079_e19d01431943','sha256':sha(SRC),'step':79,'time_s':1.6075,'tick':1607500000}; OUT.mkdir(parents=True,exist_ok=True)
 parent={'parent_status':'accepted_scope_limited','source':src,'e1_window_s':.10,'e2_window_s':.10,'cumulative_window_s':.20,'e2_wall_clock_s':e['wall_clock_s'],'e2_disk_bytes':e['disk_bytes'],'convective_time_s':1.0,'first_order_wet_mode_period_s':'not measured','prior_shedding_period_s':'external prior, not validated'}; (OUT/'parent_evidence_audit.json').write_text(json.dumps(parent,indent=2),encoding='utf-8')
 cs=[]
 for name,w in [('E3-A',.2),('E3-B',.3),('E3-C',15*.02),('bounded-conservative',.1)]:
  n=math.ceil(w/.00125); cs.append({'candidate':name,'new_window_s':w,'steps':n,'blocks':math.ceil(n/10),'wall_clock_s':n*per,'disk_bytes':n*disk,'matlab_calls':n*5,'openfoam_calls':n*3,'checkpoint_count':n,'snapshot_count':3*n,'budget_ok':n*per<=14400 and n*disk<=20*1024**3,'projected_cycles':w/.02,'fifteen_cycles':w/.02>=15})
 (OUT/'e3_candidate_matrix.json').write_text(json.dumps(cs,indent=2),encoding='utf-8'); (OUT/'e3_cost_model.json').write_text(json.dumps({'wall_clock_per_step_s':per,'disk_per_step_bytes':disk,'basis':'Stage50 measured'},indent=2),encoding='utf-8'); (OUT/'e3_storage_process_budget.json').write_text(json.dumps(cs,indent=2),encoding='utf-8'); (OUT/'e3_window_coverage.json').write_text(json.dumps(cs,indent=2),encoding='utf-8')
 files={'e3_statistical_contract.json':{'minimum_cycles':15,'minimum_samples':300,'fft_zero_crossing_agreement':'within 5%','three_stable_windows':True,'low_amplitude':'not_evaluable_low_amplitude','insufficient_cycles':'not_evaluable_insufficient_cycles'},'e3_frequency_projection.json':{'formal_St_allowed':False,'all_candidates':'diagnostic-only'},'e3_block_stability_projection.json':{'required_windows':3,'requires_real_data':True},'e3_stop_rules.json':{'stop_on':['hard gate','NaN/Inf','lineage','budget','cleanup'],'no_auto_extension':True},'e3_source_selection.json':src,'e3_block_restart_plan.json':{'source_time_s':1.7075,'block_steps':10,'checkpoint_each_block':True},'e3_source_immutability_contract.json':{'sha256':sha(SRC),'read_only':True},'option_tradeoff_matrix.json':[{'option':'A','recommendation':'do_not_enter'},{'option':'B','recommendation':'enter_E3_pending_user_authorization'},{'option':'C','recommendation':'enter_long_time_scope_requires_new_contract'},{'option':'D','recommendation':'do_not_enter'},{'option':'E','recommendation':'do_not_enter'}],'risk_register.json':{'risks':['insufficient cycles','low amplitude','cost uncertainty','restart identity']},'recommendation.json':{'recommendation':'enter_E3_pending_user_authorization','reason':'requires explicit new authorization'},'thesis_claim_impact.json':{'frequency':'not_evaluable_or_pending_real_data','stable_VIV':'not_completed'}}
 for n,v in files.items(): (OUT/n).write_text(json.dumps(v,indent=2),encoding='utf-8')
 return parent
