import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]; OUT=ROOT/'results/40_stage4f_c_final_evidence_aggregation_v1'
def load(p): return json.loads(Path(p).read_text(encoding='utf-8'))
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def audit(p):
 d=load(p); rows=d['steps']; cps=[load(r['checkpoint']) for r in rows]; ms=[m for r in rows for m in r['raw_force_snapshot_manifests']]; exact=all(Path(m['path']).exists() and sha(m['path'])==m['sha256'] and Path(m['path']).stat().st_size==m['file_size'] and Path(m['path']).stat().st_mtime_ns==m['mtime_ns'] for m in ms)
 return {'steps':len(rows),'physical_committed':d['physical_committed_steps'],'fully_audited':d['fully_audited_steps'],'checkpoints':len(cps),'snapshots':len(ms),'snapshot_exact':exact,'lineage':all(cps[i].get('parent_checkpoint_id')==(None if i==0 else 'checkpoint_'+cps[i-1]['checkpoint_id']) for i in range(len(cps))),'max_cfl':max(r['max_cfl'] for r in rows),'max_raw_cd':max(r['max_abs_Cd'] for r in rows),'max_velocity':max(r['velocity_difference_over_U'] for r in rows),'max_virtual_work':max(r['virtual_work_relative_error'] for r in rows),'max_force_conversion':max(r['force_conversion_relative_error'] for r in rows),'max_geometry':max(r['mesh_center_motion_error_m'] for r in rows)}
def run():
 OUT.mkdir(parents=True,exist_ok=True); c=audit(ROOT/'results/34_stage4f_c_case_initialization_repair_v1/C_execution.json'); d=audit(ROOT/'results/36_stage4f_c_dt4_asymptotic_diagnostic_v1/D_execution.json'); paired=load(ROOT/'results/39_stage4f_c_paired_restart_validation_v1/paired_cont_rest_comparison.json'); parent=ROOT/'cases/openfoam/stage4f_lowre_three_slice_fixed_point_v5/formal_preflight_attempt3/checkpoints/checkpoint_step00000002_d4def62051c1.json'; src=Path(load(ROOT/'results/39_stage4f_c_paired_restart_validation_v1/prefix_execution.json')['steps'][-1]['checkpoint']); hashes={'parent':sha(parent),'source':sha(src),'source_id':load(src)['checkpoint_id']}; comp={'raw_x':0.022445713650885712,'raw_y':0.003144383629047539,'applied_x':0.0042827310486069714,'applied_y':0.0,'all_under_005':True};
 for n,v in [('baseline_C_recomputation.json',c),('verification_D_recomputation.json',d),('paired_restart_final_audit.json',paired),('C_D_final_comparison.json',comp),('evidence_hash_audit.json',hashes)]: (OUT/n).write_text(json.dumps(v,indent=2),encoding='utf-8')
 gate={'gate':'STAGE4F_C_FINAL_EVIDENCE_AGGREGATION_V1_GATE: pass','dt_0_0025_status':'rejected_coarse_timestep','dt_0_00125_baseline_status':'accepted','dt_0_000625_verification_status':'accepted','dt_0_00125_restart_status':'accepted','three_slice_short_window_status':'accepted_under_revised_timestep_contract','stage4f_c_status':'accepted_scope_limited','strict_asymptotic_convergence_claim':'not_completed','gci_claim':'not_completed','five_slice':'do_not_enter','nine_slice':'do_not_enter','long_time_viv':'do_not_enter','stage4e_physical_validation':'not_completed','C':c,'D':d,'paired_restart_max_relative':paired['max_relative'],'comparison':comp}; (OUT/'stage4f_c_final_gate.json').write_text(json.dumps(gate,indent=2),encoding='utf-8'); return gate
if __name__=='__main__': print(json.dumps(run()))
