"""Offline accepted-window analysis for the 40k dt=0.0025 continuation.

The script never launches a solver. It uses only ``window_commit`` events as
physical samples and keeps the 210--255 s parent and 255.9--280 s continuation
statistics explicitly separated.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import re
from collections import Counter
from pathlib import Path

import numpy as np


BASE = Path(r"D:/CFD/CFD_ANCF_VIV/runtime/fixed_cylinder_o_grid")
PARENT = BASE / "moving_wall_dt0p0025_sensitivity_v1"
NEW = BASE / "moving_wall_dt0p0025_resume25s_v1"
DEFAULT_OUT = NEW / "postprocess_resume25s_v1"
D = 1.0
U = 1.0
RHO = 1000.0
M = 2500.0
K = 4940.0
FORCE_SCALE = 0.5 * RHO * U * U * D * 1.0


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def parse_events(run: Path, segment: str) -> tuple[list[dict], Counter, dict]:
    event_file = run / "structure" / "events.jsonl"
    rows: list[dict] = []
    counts: Counter = Counter()
    initial: dict | None = None
    for line in event_file.open("r", encoding="utf-8"):
        if not line.strip():
            continue
        event = json.loads(line)
        kind = event.get("event", "")
        counts[kind] += 1
        if kind == "initial_data" and initial is None:
            initial = event
        if kind != "window_commit":
            continue
        state = event["accepted_state"]
        rows.append({
            "time_s": float(event["physical_time_s"]),
            "y_m": float(state["y_m"]),
            "v_mps": float(state["v_mps"]),
            "a_mps2": float(state["a_mps2"]),
            "Fy_N": float(event["force_y_total_N"]),
            "mechanical_energy_J": float(event["mechanical_energy_J"]),
            "cumulative_fluid_work_J": float(event["cumulative_fluid_work_J"]),
            "energy_balance_defect_J": float(event["cumulative_energy_balance_defect_J"]),
            "iteration_count": int(event["iteration_count"]),
            "window_index": int(event["window_index"]),
            "segment": segment,
            "sample_kind": "window_commit",
        })
    if initial is None:
        raise RuntimeError(f"missing initial_data in {event_file}")
    contract = read_json(run / "contract.json")
    st = initial["initial_state"]
    restart = contract.get("restart")
    if restart and "parent_last_accepted" in contract:
        energy = float(contract["parent_last_accepted"]["mechanical_energy_J"])
        work = float(restart["cumulative_fluid_work_J"])
        defect = float(restart["cumulative_energy_balance_defect_J"])
    else:
        energy = 0.5 * M * float(st["v_mps"]) ** 2 + 0.5 * K * float(initial["payload_y_m"]) ** 2
        work = 0.0
        defect = 0.0
    rows.insert(0, {
        "time_s": float(initial["physical_time_s"]),
        "y_m": float(initial["payload_y_m"]),
        "v_mps": float(st["v_mps"]),
        "a_mps2": float(st["a_mps2"]),
        "Fy_N": float(initial["initial_force_y_N"]),
        "mechanical_energy_J": energy,
        "cumulative_fluid_work_J": work,
        "energy_balance_defect_J": defect,
        "iteration_count": 0,
        "window_index": 0,
        "segment": segment,
        "sample_kind": "restart_initial",
    })
    rows.sort(key=lambda row: row["time_s"])
    return rows, counts, contract


def parse_force_coeffs(run: Path) -> dict[float, tuple[float, float, float]]:
    files = sorted((run / "postProcessing" / "cylinderForceCoeffs").rglob("forceCoeffs.dat"))
    if not files:
        raise RuntimeError(f"no forceCoeffs.dat in {run}")
    dedup: dict[float, tuple[float, float, float]] = {}
    for path in files:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            fields = line.split()
            if len(fields) < 4:
                continue
            values = [float(value) for value in fields[:4]]
            # Repeated rows are generated by coupling/PIMPLE iterations; the
            # last row at a time is retained as the converged force coefficient.
            dedup[round(values[0], 8)] = (values[1], values[2], values[3])
    return dict(sorted(dedup.items()))


def attach_coeffs(rows: list[dict], coeffs: dict[float, tuple[float, float, float]]) -> None:
    keys = np.asarray(list(coeffs), dtype=float)
    values = list(coeffs.values())
    for row in rows:
        index = int(np.argmin(np.abs(keys - row["time_s"])))
        delta = float(keys[index] - row["time_s"])
        if abs(delta) > 2.0e-4:
            raise RuntimeError(f"force coefficient time mismatch near {row['time_s']}")
        row["Cm"], row["Cd"], row["Cl"] = (float(item) for item in values[index])
        row["force_time_s"] = float(keys[index])
        row["force_time_delta_s"] = delta


def quality_scan(run: Path) -> dict:
    paths = [run / "fluid.stdout", run / "fluid.stderr", run / "participant.stdout", run / "participant.stderr"]
    text = "\n".join(path.read_text(encoding="utf-8", errors="replace") for path in paths if path.exists())
    co = [(float(a), float(b)) for a, b in re.findall(
        r"Courant Number mean:\s*([0-9.eE+-]+) max:\s*([0-9.eE+-]+)", text)]
    continuity = [(float(a), float(b)) for a, b in re.findall(
        r"time step continuity errors\s*:\s*sum local =\s*([0-9.eE+-]+),\s*global =\s*([0-9.eE+-]+)", text)]
    patterns = {
        "FPE": r"Floating point exception signal|received signal SIGFPE|SIGFPE.*stack",
        "NaN_Inf": r"(?<![A-Za-z])(?:nan|NaN|inf|Inf)(?![A-Za-z])",
        "negative_volume": r"negative volume|negative cell volume",
        "preCICE_failure": r"(?:ERROR.*preCICE|preCICE.*ERROR|convergence\s+failed)",
        "solver_fatal": r"FOAM FATAL (?:ERROR|IO ERROR)|Fatal error",
    }
    hits = {name: bool(re.search(pattern, text, re.IGNORECASE)) for name, pattern in patterns.items()}
    return {
        "courant_sample_count": len(co),
        "max_Co_mean": max((item[0] for item in co), default=None),
        "max_Co": max((item[1] for item in co), default=None),
        "continuity_sample_count": len(continuity),
        "max_abs_local_continuity": max((abs(item[0]) for item in continuity), default=None),
        "max_abs_global_continuity": max((abs(item[1]) for item in continuity), default=None),
        "hard_failure_scan": hits,
        "all_hard_failure_patterns_clear": not any(hits.values()),
    }


def crossing_times(rows: list[dict]) -> np.ndarray:
    t = np.asarray([row["time_s"] for row in rows], dtype=float)
    y = np.asarray([row["y_m"] for row in rows], dtype=float)
    index = np.flatnonzero((y[:-1] < 0.0) & (y[1:] >= 0.0))
    result = []
    for i in index:
        denominator = y[i + 1] - y[i]
        result.append(float(t[i] if denominator == 0 else t[i] - y[i] * (t[i + 1] - t[i]) / denominator))
    return np.asarray(result)


def cycles_for_rows(rows: list[dict], segment: str) -> tuple[list[dict], list[dict]]:
    t = np.asarray([row["time_s"] for row in rows], dtype=float)
    crossings = crossing_times(rows)
    median_dt = float(np.median(np.diff(t)))
    complete: list[dict] = []
    excluded: list[dict] = []
    local_index = 0
    for interval_index in range(max(0, len(crossings) - 1)):
        start, end = float(crossings[interval_index]), float(crossings[interval_index + 1])
        mask = (t >= start) & (t <= end)
        positions = np.flatnonzero(mask)
        gaps = np.diff(t[positions]) if len(positions) > 1 else np.asarray([])
        gap = float(gaps.max()) if len(gaps) else 0.0
        if gap > 1.5 * median_dt:
            excluded.append({"segment": segment, "interval_index": interval_index + 1,
                             "start_time_s": start, "end_time_s": end,
                             "reason": "missing accepted samples across a runtime gap", "max_internal_gap_s": gap})
            continue
        if len(positions) < 10:
            continue
        local_index += 1
        y = np.asarray([rows[j]["y_m"] for j in positions])
        cl = np.asarray([rows[j]["Cl"] for j in positions])
        cd = np.asarray([rows[j]["Cd"] for j in positions])
        energy = np.asarray([rows[j]["mechanical_energy_J"] for j in positions])
        work = np.asarray([rows[j]["cumulative_fluid_work_J"] for j in positions])
        it = np.asarray([rows[j]["iteration_count"] for j in positions])
        complete.append({
            "segment": segment,
            "local_cycle_index": local_index,
            "start_time_s": start,
            "end_time_s": end,
            "y_max_m": float(y.max()),
            "y_min_m": float(y.min()),
            "A_over_D": float((y.max() - y.min()) / (2.0 * D)),
            "period_s": float(end - start),
            "fD_over_U": float(D / (U * (end - start))),
            "CL_amplitude_half_peak_to_peak": float((cl.max() - cl.min()) / 2.0),
            "mean_CD": float(cd.mean()),
            "max_coupling_iterations": int(it.max()),
            "mean_coupling_iterations": float(it.mean()),
            "mechanical_energy_start_J": float(energy[0]),
            "mechanical_energy_end_J": float(energy[-1]),
            "mechanical_energy_change_J": float(energy[-1] - energy[0]),
            "fluid_work_change_J": float(work[-1] - work[0]),
        })
    return complete, excluded


def add_global_indices(cycles: list[dict]) -> list[dict]:
    output = []
    for index, cycle in enumerate(cycles, start=1):
        item = dict(cycle)
        item["cycle_index"] = index
        output.append(item)
    return output


def add_increments(cycles: list[dict]) -> list[dict]:
    output = []
    previous = None
    for cycle in cycles:
        item = dict(cycle)
        comparable = previous is not None and previous["segment"] == cycle["segment"]
        item["increment_comparable"] = comparable
        for key, name in [("A_over_D", "delta_A_over_D"), ("CL_amplitude_half_peak_to_peak", "delta_CL_amplitude"),
                          ("fD_over_U", "delta_fD_over_U"), ("mean_CD", "delta_mean_CD")]:
            item[name] = float(cycle[key] - previous[key]) if comparable else None
        output.append(item)
        previous = cycle
    return output


def window_stats(cycles: list[dict]) -> dict:
    if not cycles:
        return {"n": 0, "mean": {}, "std": {}, "CV": {}, "slope_per_cycle": {}, "relative_end_to_end_trend": {}}
    keys = [("A_over_D", "A_over_D"), ("fD_over_U", "fD_over_U"),
            ("CL_amplitude_half_peak_to_peak", "CL_amplitude"), ("mean_CD", "mean_CD")]
    result = {"n": len(cycles), "mean": {}, "std": {}, "CV": {}, "slope_per_cycle": {}, "relative_end_to_end_trend": {}}
    x = np.arange(len(cycles), dtype=float)
    for source, target in keys:
        values = np.asarray([cycle[source] for cycle in cycles], dtype=float)
        mean = float(values.mean()); std = float(values.std(ddof=1)) if len(values) > 1 else 0.0
        slope = float(np.polyfit(x, values, 1)[0]) if len(values) > 1 else 0.0
        result["mean"][target] = mean
        result["std"][target] = std
        result["CV"][target] = float(std / abs(mean)) if mean else None
        result["slope_per_cycle"][target] = slope
        result["relative_end_to_end_trend"][target] = float((values[-1] - values[0]) / abs(mean)) if mean else None
    return result


def write_csv(path: Path, rows: list[dict], fields: list[str] | None = None) -> None:
    if fields is None:
        fields = list(rows[0]) if rows else ["cycle_index"]
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields, extrasaction="ignore")
        writer.writeheader(); writer.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--parent", type=Path, default=PARENT)
    parser.add_argument("--new", type=Path, default=NEW)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    out = args.out.resolve(); out.mkdir(parents=True, exist_ok=True)
    parent_rows, parent_events, parent_contract = parse_events(args.parent.resolve(), "parent_210_to_255s")
    new_rows, new_events, new_contract = parse_events(args.new.resolve(), "new_255p9_to_280s")
    attach_coeffs(parent_rows, parse_force_coeffs(args.parent.resolve()))
    attach_coeffs(new_rows, parse_force_coeffs(args.new.resolve()))
    parent_cycles, parent_excluded = cycles_for_rows(parent_rows, "parent_210_to_255s")
    new_cycles, new_excluded = cycles_for_rows(new_rows, "new_255p9_to_280s")
    all_rows = sorted(parent_rows + new_rows, key=lambda row: row["time_s"])
    all_cycles, all_excluded = cycles_for_rows(all_rows, "combined_210_to_280s")
    # Rebuild a continuous index from the complete parent/new cycles while
    # retaining the gap exclusion explicitly. This avoids treating the 0.9 s
    # missing interval as a physical sample.
    combined_cycles = add_global_indices(parent_cycles + new_cycles)
    increments = add_increments(combined_cycles)
    quality_parent = quality_scan(args.parent.resolve())
    quality_new = quality_scan(args.new.resolve())
    summary_parent = read_json(args.parent / "structure" / "structure_summary.json")
    summary_new = read_json(args.new / "structure" / "structure_summary.json")

    def extrema(rows: list[dict]) -> dict:
        return {
            "max_abs_y_m": float(max(abs(row["y_m"]) for row in rows)),
            "max_abs_v_mps": float(max(abs(row["v_mps"]) for row in rows)),
            "max_abs_a_mps2": float(max(abs(row["a_mps2"]) for row in rows)),
            "max_abs_Fy_N": float(max(abs(row["Fy_N"]) for row in rows)),
            "max_abs_CL": float(max(abs(row["Cl"]) for row in rows)),
            "Cd_min": float(min(row["Cd"] for row in rows)),
            "Cd_max": float(max(row["Cd"] for row in rows)),
        }

    five_last = combined_cycles[-5:]
    five_first = combined_cycles[:5]
    metrics = {
        "schema_version": "moving-wall-40k-dt0p0025-resume25s-offline-analysis-v1",
        "runtime_parent": str(args.parent.resolve()), "runtime_new": str(args.new.resolve()), "output": str(out),
        "accepted_only_policy": "Only Structure window_commit events are physical samples; trial_read_force_and_correct and checkpoint_restore are excluded.",
        "new_segment": {
            "start_time_s": new_rows[0]["time_s"], "end_time_s": new_rows[-1]["time_s"],
            "accepted_windows": summary_new["accepted_windows"], "accepted_samples_including_restart": len(new_rows),
            "cycles_complete": len(new_cycles), "excluded_intervals": new_excluded,
            "extrema": extrema(new_rows), "quality": quality_new,
            "energy_balance_defect_initial_J": new_rows[0]["energy_balance_defect_J"],
            "energy_balance_defect_terminal_J": new_rows[-1]["energy_balance_defect_J"],
            "energy_balance_defect_increment_J": new_rows[-1]["energy_balance_defect_J"] - new_rows[0]["energy_balance_defect_J"],
            "cycles_last_window": window_stats(new_cycles),
        },
        "combined_continuation_210_to_280s": {
            "coverage_start_s": all_rows[0]["time_s"], "coverage_end_s": all_rows[-1]["time_s"],
            "accepted_windows": summary_parent["accepted_windows"] + summary_new["accepted_windows"],
            "complete_cycles": len(combined_cycles), "gap_exclusions": all_excluded,
            "extrema": extrema(all_rows), "cycles_last_five": window_stats(five_last),
            "cycles_first_five": window_stats(five_first),
            "first_to_last_five_mean_change": {
                key: (window_stats(five_last)["mean"].get(key) - window_stats(five_first)["mean"].get(key))
                if key in window_stats(five_last)["mean"] and key in window_stats(five_first)["mean"] else None
                for key in ["A_over_D", "fD_over_U", "CL_amplitude", "mean_CD"]
            },
            "quality_parent": quality_parent, "quality_new": quality_new,
        },
        "event_counts": {"parent": dict(parent_events), "new": dict(new_events)},
        "structure_summaries": {"parent": summary_parent, "new": summary_new},
        "interpretation": "The new continuation contains four complete cycles; a 0.9 s accepted-data gap between 255.0 and 255.9 s excludes one crossing interval from complete-cycle statistics. The last-five window therefore includes a documented pre-gap cycle and is not a contiguous five-cycle plateau test.",
    }
    write_json_path = out / "metrics_40k_dt0p0025_resume25s.json"
    write_json_path.write_text(json.dumps(metrics, indent=2, ensure_ascii=False, allow_nan=False), encoding="utf-8")
    time_fields = ["time_s", "y_m", "v_mps", "a_mps2", "Fy_N", "Cm", "Cd", "Cl", "mechanical_energy_J", "cumulative_fluid_work_J", "energy_balance_defect_J", "iteration_count", "window_index", "segment", "sample_kind", "force_time_s", "force_time_delta_s"]
    write_csv(out / "accepted_time_history_new_segment.csv", new_rows, time_fields)
    write_csv(out / "accepted_time_history_210_to_280s.csv", all_rows, time_fields)
    cycle_fields = ["cycle_index", "segment", "local_cycle_index", "start_time_s", "end_time_s", "y_max_m", "y_min_m", "A_over_D", "period_s", "fD_over_U", "CL_amplitude_half_peak_to_peak", "mean_CD", "max_coupling_iterations", "mean_coupling_iterations", "mechanical_energy_start_J", "mechanical_energy_end_J", "mechanical_energy_change_J", "fluid_work_change_J"]
    write_csv(out / "cycle_statistics.csv", combined_cycles, cycle_fields)
    write_csv(out / "cycle_statistics_new_segment.csv", [{**c, "cycle_index": i + 1} for i, c in enumerate(new_cycles)], ["cycle_index"] + cycle_fields[1:])
    write_csv(out / "cycle_increments.csv", increments, cycle_fields + ["increment_comparable", "delta_A_over_D", "delta_CL_amplitude", "delta_fD_over_U", "delta_mean_CD"])
    write_csv(out / "cycle_exclusions.csv", parent_excluded + new_excluded + all_excluded)

    last = metrics["new_segment"]["cycles_last_window"]["mean"]
    ref = {"A_over_D": 0.57, "fD_over_U": 0.198, "CL_amplitude": 1.35, "mean_CD": 2.23}
    report = [
        "# 40k、dt=0.0025 s续算离线结果",
        "",
        "## 1. 数据范围与完整性",
        "",
        f"- 新增续算段：OF {new_rows[0]['time_s']:.9f}–{new_rows[-1]['time_s']:.9f} s。",
        f"- 新增 accepted 窗口：{summary_new['accepted_windows']}；trial/restore：{summary_new['trial_attempts']} / {summary_new['checkpoint_restores']}。",
        f"- 返回码：`structure=0 fluid=0`；状态：`{summary_new['status']}`；最后共同接受时间：{summary_new['last_accepted_physical_time_s']:.12f} s。",
        f"- 每窗口迭代数：{sorted(set(row['iteration_count'] for row in new_rows[1:]))}。",
        f"- 新段最大 Co：{quality_new['max_Co']:.9g}；最大 local/global continuity：{quality_new['max_abs_local_continuity']:.9g} / {quality_new['max_abs_global_continuity']:.9g}。",
        f"- 新段最大 |y|/|v|/|a|/|Fy|：{extrema(new_rows)['max_abs_y_m']:.9g} m / {extrema(new_rows)['max_abs_v_mps']:.9g} m/s / {extrema(new_rows)['max_abs_a_mps2']:.9g} m/s² / {extrema(new_rows)['max_abs_Fy_N']:.9g} N。",
        f"- 新段最大 |CL|：{extrema(new_rows)['max_abs_CL']:.9g}；CD范围：[{extrema(new_rows)['Cd_min']:.9g}, {extrema(new_rows)['Cd_max']:.9g}]。",
        f"- 新段能量平衡缺陷增量：{metrics['new_segment']['energy_balance_defect_increment_J']:.9g} J。",
        f"- 硬错误扫描：{quality_new['hard_failure_scan']}。",
        "- 本续算 runtime 未将 trial/restore 当作独立物理样本；本报告只使用 `window_commit`。",
        "",
        "## 2. 新增25 s段的完整周期",
        "",
        f"新增段识别到 {len(new_cycles)} 个完整正向过零周期。由于起点为255.9 s，约0.9 s的前置间隔不属于本新增段。详见 `cycle_statistics_new_segment.csv`。",
        "",
        "| 局部周期 | 起止时间(s) | ymax(m) | ymin(m) | A/D | 周期(s) | fD/U | CL幅值 | mean CD | 迭代 |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for index, cycle in enumerate(new_cycles, start=1):
        report.append(f"| {index} | {cycle['start_time_s']:.6f}–{cycle['end_time_s']:.6f} | {cycle['y_max_m']:.6f} | {cycle['y_min_m']:.6f} | {cycle['A_over_D']:.6f} | {cycle['period_s']:.6f} | {cycle['fD_over_U']:.6f} | {cycle['CL_amplitude_half_peak_to_peak']:.6f} | {cycle['mean_CD']:.6f} | {cycle['max_coupling_iterations']} |")
    report += [
        "",
        "## 3. 连续周期趋势（210–280 s）",
        "",
        f"父段完整周期 {len(parent_cycles)} 个，新段完整周期 {len(new_cycles)} 个，合并为连续编号 {len(combined_cycles)} 个。255.0→255.9 s存在 accepted 数据缺口，跨缺口的周期已排除；详见 `cycle_exclusions.csv`。",
        "",
        "每周期增量见 `cycle_increments.csv`。同一段内计算 ΔA、ΔCL、Δf、ΔCD；跨运行缺口的第一项增量标记为不可比较。",
        "",
        f"末5个完整周期均值：A/D={metrics['combined_continuation_210_to_280s']['cycles_last_five']['mean'].get('A_over_D', math.nan):.8f}，fD/U={metrics['combined_continuation_210_to_280s']['cycles_last_five']['mean'].get('fD_over_U', math.nan):.8f}，CL={metrics['combined_continuation_210_to_280s']['cycles_last_five']['mean'].get('CL_amplitude', math.nan):.8f}，mean CD={metrics['combined_continuation_210_to_280s']['cycles_last_five']['mean'].get('mean_CD', math.nan):.8f}。",
        f"末5周期 CV：A/D={metrics['combined_continuation_210_to_280s']['cycles_last_five']['CV'].get('A_over_D', math.nan):.3%}，fD/U={metrics['combined_continuation_210_to_280s']['cycles_last_five']['CV'].get('fD_over_U', math.nan):.3%}，CL={metrics['combined_continuation_210_to_280s']['cycles_last_five']['CV'].get('CL_amplitude', math.nan):.3%}，mean CD={metrics['combined_continuation_210_to_280s']['cycles_last_five']['CV'].get('mean_CD', math.nan):.3%}。",
        f"新增段本身只有 {len(new_cycles)} 个完整周期，不能形成独立的last-five连续平台窗口。新增段A/D由{new_cycles[0]['A_over_D']:.6f}变为{new_cycles[-1]['A_over_D']:.6f}，CL幅值由{new_cycles[0]['CL_amplitude_half_peak_to_peak']:.6f}变为{new_cycles[-1]['CL_amplitude_half_peak_to_peak']:.6f}。",
        "",
        "## 4. Shiels bounded / near-limit-cycle comparison",
        "",
        "末端五周期包含跨运行缺口前后的完整周期，因此只作 bounded / near-limit-cycle comparison，不作为新的 plateau PASS。",
        "",
        "| 指标 | 当前末5周期 | Shiels | 相对误差 |",
        "|---|---:|---:|---:|",
    ]
    for label, key, reference in [("A/D", "A_over_D", ref["A_over_D"]), ("fD/U", "fD_over_U", ref["fD_over_U"]), ("CL半峰峰幅值", "CL_amplitude", ref["CL_amplitude"]), ("mean CD", "mean_CD", ref["mean_CD"])]:
        value = metrics["combined_continuation_210_to_280s"]["cycles_last_five"]["mean"].get(key)
        report.append(f"| {label} | {value:.8f} | {reference:.8f} | {(value-reference)/reference:+.3%} |" if value is not None else f"| {label} | n/a | {reference:.8f} | n/a |")
    report += [
        "",
        "## 5. 结论",
        "",
        "新增25 s段的周期量级接近上一段，周期频率和CD没有明显跳变；但新增段只有4个完整周期，且合并数据存在255.0→255.9 s缺口，不能仅凭末5周期CV宣布平台。应依据 cycle_increments 中的同段增量和后续连续数据判断是否趋近零。",
        "",
        "输出文件：`accepted_time_history_new_segment.csv`、`accepted_time_history_210_to_280s.csv`、`cycle_statistics.csv`、`cycle_statistics_new_segment.csv`、`cycle_increments.csv`、`cycle_exclusions.csv`、`metrics_40k_dt0p0025_resume25s.json`。",
    ]
    (out / "REPORT_40K_DT0P0025_RESUME25S.md").write_text("\n".join(report) + "\n", encoding="utf-8")
    print(json.dumps({"out": str(out), "new_cycles": len(new_cycles), "combined_cycles": len(combined_cycles), "last5": metrics["combined_continuation_210_to_280s"]["cycles_last_five"]["mean"]}, ensure_ascii=False))


if __name__ == "__main__":
    main()
