"""Audit a C++-only t=0 reference state without starting a CFD solver."""
from __future__ import annotations

import hashlib
import json
import math
import struct
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[2]
RUN = PROJECT / "runtime/stage4f_d_cpp_worker_initialization_v1/run_20260827_cpp_only"
RESULT = PROJECT / "results/237_cpp_worker_initialization_v1"
DOC = PROJECT / "docs/237_cpp_worker_initialization_v1"
STATE = RUN / "ancf_t0_state_cpp.json"
EXE = RUN / "cfd_ancf_cpp_state_initializer.exe"
WORKER_EXE = RUN / "cfd_ancf_ancf_kernel_worker.exe"
SELFTEST_EXE = RUN / "cfd_ancf_ancf_kernel_selftest.exe"
SOURCE = PROJECT / "src/coupling/cpp_worker_persistent_ipc_v1/ancf_state_initializer.cpp"
KERNEL = PROJECT / "src/coupling/cpp_worker_persistent_ipc_v1/ancf_kernel.cpp"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def canonical(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=True, sort_keys=True, separators=(",", ":"), allow_nan=False) + "\n").encode("utf-8")


def main() -> int:
    if not STATE.is_file() or not EXE.is_file():
        raise SystemExit("C++ initializer output or executable is missing")
    state = json.loads(STATE.read_bytes().decode("utf-8"))
    q = state.get("q", [])
    qdot = state.get("qdot", [])
    qddot = state.get("qddot", [])
    mass = state.get("mass_matrix", [])
    base_load = state.get("base_load", [])
    finite = all(math.isfinite(float(x)) for x in [*q, *qdot, *qddot, *base_load, *mass])
    raw = b"".join(struct.pack("<d", float(x)) for x in [*q, *qdot, *qddot, *base_load, *mass])
    actual_hash = hashlib.sha256(raw).hexdigest()
    checks = {
        "state_exists": True,
        "ndof_102": len(q) == 102 and len(qdot) == 102 and len(qddot) == 102,
        "mass_102x102": len(mass) == 102 * 102,
        "base_load_102": len(base_load) == 102,
        "step_time_tick_zero": state.get("global_step") == 0 and state.get("time_s") == 0.0 and state.get("integer_tick") == 0,
        "bridge_step_zero": state.get("case_local_bridge_step") == 0,
        "finite_value_audit": state.get("finite_value_audit") is True and finite,
        "state_hash_match": state.get("state_hash_sha256") == actual_hash,
        "cpp_only_marker": state.get("worker") == "cfd_ancf_cpp_state_initializer" and state.get("release") == "cpp_kernel_v1",
    }
    evidence = {
        "stage_id": "stage4f_d_cpp_worker_initialization_v1",
        "run_id": "cpp_init_20260827_001",
        "state": str(STATE),
        "state_sha256": sha256(STATE),
        "state_hash_sha256": actual_hash,
        "initializer_executable": str(EXE),
        "initializer_executable_sha256": sha256(EXE),
        "worker_executable_sha256": sha256(WORKER_EXE) if WORKER_EXE.is_file() else None,
        "selftest_executable_sha256": sha256(SELFTEST_EXE) if SELFTEST_EXE.is_file() else None,
        "initializer_source_sha256": sha256(SOURCE),
        "kernel_source_sha256": sha256(KERNEL),
        "checks": checks,
        "equilibrated": state.get("equilibrated") is True and float(state.get("static_residual_inf", float("inf"))) <= 1.0e-8 * max(1.0, abs(2179104.0029808935)),
        "static_residual_inf": state.get("static_residual_inf"),
        "static_load_steps": state.get("load_steps"),
        "static_iterations": state.get("static_iterations"),
        "gate": "STAGE4F_D_CPP_WORKER_INITIALIZATION_V1_GATE: pass" if state.get("equilibrated") is True else "STAGE4F_D_CPP_WORKER_INITIALIZATION_V1_GATE: do_not_pass",
        "reason": "C++ load-ramped static equilibrium is converged and independently audited." if state.get("equilibrated") is True else "C++ static equilibrium did not converge.",
        "real_process_starts": {"CPP_INITIALIZER": 1, "MATLAB": 0, "OpenFOAM": 0, "WSL": 0, "CFD": 0},
        "owned_residual": 0,
        "old_evidence_modified": False,
        "stage236_reused": False,
    }
    RESULT.mkdir(parents=True, exist_ok=True)
    DOC.mkdir(parents=True, exist_ok=True)
    (RESULT / "cpp_initialization_audit.json").write_bytes(canonical(evidence))
    (RESULT / "stage4f_d_cpp_worker_initialization_v1_gate.json").write_bytes(canonical(evidence))
    report = """# Stage 237 C++ worker-only initialization

- The t=0 state was generated by `cfd_ancf_cpp_state_initializer.exe`, which links the production C++ ANCF kernel.
- No MATLAB, OpenFOAM, WSL, or CFD process was started.
- `q`, `qdot`, `qddot`, and the 102x102 mass matrix are finite and the binary state hash is verified.
- The C++ initializer performs a 40-level load-ramped static Newton solve using gravity, buoyancy, and top tension. The final free-DOF residual is recorded in the audit.
- Gate is pass only when `equilibrated=true` and the residual is within the existing numerical threshold.

The prior Stage 236 package and all older evidence remain read-only. This package must not be used to launch a physical CFD continuation.
"""
    (DOC / "cpp_initialization_report.md").write_text(report, encoding="utf-8")
    print(json.dumps({"gate": evidence["gate"], "checks": checks, "process_starts": evidence["real_process_starts"]}, ensure_ascii=True, sort_keys=True))
    return 0 if all(checks.values()) else 1


if __name__ == "__main__":
    raise SystemExit(main())
