"""One-way exact-motion CFD and mesh-only replays; never starts preCICE or ANCF."""
from __future__ import annotations

import json
import argparse
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RUN = ROOT / "runtime/preconditioned_coupled_0p1s_smoke_v1_run_003"
MOTION = ROOT / "runtime/preconditioned_force_escalation_motion_replay_v1_run_004"
MESH = ROOT / "runtime/preconditioned_force_escalation_mesh_replay_v1_run_004"
OUT = ROOT / "results/preconditioned_force_escalation_and_mesh_auxiliary_root_cause_audit_v1_run_001"
DT = 0.005


def put(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(text)


def wsl(path: Path) -> str:
    text = str(path.resolve()).replace("\\", "/")
    return "/mnt/" + text[0].lower() + text[2:]


def table(rows: list[dict], sid: int) -> str:
    values = [(0.1, (0.0, 0.0, 0.0))]
    for index, row in enumerate(rows):
        # The persisted raw force at physical time t_n is written before the
        # next mesh update.  Therefore it is generated by the geometry sent
        # in the preceding explicit window, not by prediction n itself.
        # This is the exact recorded OpenFOAM/preCICE time-layer convention.
        motion = rows[index - 1]["motion"][sid] if index >= 1 else {"ux_m": 0.0, "uy_m": 0.0}
        values.append((0.1 + float(row["time_s"]), (float(motion["ux_m"]), float(motion["uy_m"]), 0.0)))
    return " ".join(f"({time_s:.12g} ({x:.17g} {y:.17g} {z:.17g}))" for time_s, (x, y, z) in values)


def displacement_field(name: str, values: str) -> str:
    foam_class = "pointVectorField" if name == "pointDisplacement" else "volVectorField"
    return f'''FoamFile {{ format ascii; class {foam_class}; location "0.1"; object {name}; }}
dimensions [0 1 0 0 0 0 0];
internalField uniform (0 0 0);
boundaryField {{
 inlet {{ type fixedValue; value uniform (0 0 0); }}
 outlet {{ type fixedValue; value uniform (0 0 0); }}
 lower {{ type symmetryPlane; }} upper {{ type symmetryPlane; }}
 cylinder {{ type uniformFixedValue; uniformValue table ({values}); }}
 front {{ type empty; }} back {{ type empty; }}
}}
'''


def control(application: str) -> str:
    functions = "" if application == "moveMesh" else '''functions {
 cylinderForces { type forces; libs ("libforces.so"); writeControl timeStep; writeInterval 1; log yes; patches (cylinder); rho rhoInf; rhoInf 1000; CofR (0 0 0); }
}'''
    return f'''FoamFile {{ format ascii; class dictionary; object controlDict; }}
application {application};
startFrom startTime; startTime 0.1; stopAt endTime; endTime 0.2; deltaT 0.005;
writeControl timeStep; writeInterval 1; purgeWrite 0; writeFormat ascii; writePrecision 12; writeCompression off; timeFormat general; timePrecision 12; runTimeModifiable false;
{functions}
'''


def prepare(target: Path, application: str, rows: list[dict]) -> None:
    if target.exists():
        raise RuntimeError(f"refusing to reuse diagnostic runtime {target}")
    for sid in range(3):
        source = RUN / "cases" / f"slice_{sid:04d}"; case = target / f"slice_{sid:04d}"
        for name in ("0.1", "constant", "system"):
            shutil.copytree(source / name, case / name)
        values = table(rows, sid)
        put(case / "0.1/pointDisplacement", displacement_field("pointDisplacement", values))
        put(case / "0.1/cellDisplacement", displacement_field("cellDisplacement", values))
        put(case / "system/controlDict", control(application))


def launch(target: Path, application: str) -> dict[str, object]:
    commands = ["set -e", "source /opt/openfoam10/etc/bashrc"]
    for sid in range(3):
        case = target / f"slice_{sid:04d}"
        commands.append(f"(cd '{wsl(case)}' && {application} > {application}.stdout 2> {application}.stderr) & p{sid}=$!")
    commands.extend(["wait $p0; r0=$?", "wait $p1; r1=$?", "wait $p2; r2=$?", "printf '%s %s %s\\n' $r0 $r1 $r2"])
    launcher = target / "launch.sh"; put(launcher, "\n".join(commands) + "\n")
    done = subprocess.run(["wsl.exe", "-d", "Ubuntu-22.04", "--", "bash", wsl(launcher)], cwd=ROOT,
                          capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=300)
    put(target / "launcher.stdout", done.stdout); put(target / "launcher.stderr", done.stderr)
    return {"return_code": done.returncode, "stdout": done.stdout, "stderr": done.stderr}


def main() -> int:
    args = argparse.ArgumentParser(); args.add_argument("--prepare-only", action="store_true"); args = args.parse_args()
    rows = [json.loads(line) for line in (RUN / "records.jsonl").read_text(encoding="utf-8").splitlines()]
    if len(rows) != 20: raise RuntimeError("requires complete immutable 20-step source")
    prepare(MOTION, "pimpleFoam", rows); prepare(MESH, "moveMesh", rows)
    if args.prepare_only:
        print(json.dumps({"prepared": True})); return 0
    motion = launch(MOTION, "pimpleFoam"); mesh = launch(MESH, "moveMesh")
    result = {"schema_version": "preconditioned-one-way-replays-v1", "source": str(RUN.relative_to(ROOT)),
              "motion_cfd": {"runtime": str(MOTION.relative_to(ROOT)), **motion},
              "mesh_only": {"runtime": str(MESH.relative_to(ROOT)), **mesh}}
    put(OUT / "one_way_replay_launch.json", json.dumps(result, ensure_ascii=False, indent=2) + "\n")
    print(json.dumps({"motion_return": motion["return_code"], "mesh_return": mesh["return_code"]}))
    return 0 if motion["return_code"] == 0 and mesh["return_code"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
