"""Build Stage 4E-A offline audit artifacts from read-only inputs.

This module never launches OpenFOAM, MATLAB, checkMesh, or setFields.  The
ANCF raw result is generated by ``run_ancf_baseline_design.m`` and is only
summarised here.
"""

from __future__ import annotations

import hashlib
import json
import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "results" / "08_stage4e_physical_baseline"
RAW = OUT / "ancf_design_raw.json"
PDF = Path(r"D:\zotero\数据保存位置\storage\IVBQKJJU\细长柔性立管涡激振动数值计算软件开发与应用研究_端木玉.pdf")


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def write_json(name: str, obj: Any) -> None:
    (OUT / name).write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding="utf-8")


def rel(a: float, b: float) -> float:
    return abs(a - b) / max(abs(b), 1e-30)


def finite(x: Any) -> bool:
    if isinstance(x, (int, float)):
        return math.isfinite(float(x))
    if isinstance(x, list):
        return all(finite(v) for v in x)
    if isinstance(x, dict):
        return all(finite(v) for v in x.values())
    return True


def load_raw() -> dict[str, Any]:
    if not RAW.exists():
        raise FileNotFoundError(f"Missing MATLAB raw result: {RAW}")
    raw = json.loads(RAW.read_text(encoding="utf-8"))
    if raw.get("openfoam_started") is not False or raw.get("read_only_core") is not True:
        raise RuntimeError("ANCF raw audit identity is invalid")
    if not finite(raw):
        raise RuntimeError("ANCF raw audit contains a non-finite value")
    return raw


def source_record(path: Path, role: str) -> dict[str, Any]:
    return {
        "path": str(path),
        "role": role,
        "exists": path.exists(),
        "sha256": sha256(path) if path.exists() else None,
        "bytes": path.stat().st_size if path.exists() else None,
    }


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    raw = load_raw()
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    project = ROOT
    contract = project / "docs" / "05_multi_slice_contract.md"
    sol_review = project / "docs" / "07_stage4d_c_a_v3_sol_review.md"
    sol_review_json = project / "results" / "07_stage4d_c_modal_bandwidth_audit_v3" / "stage4d_c_a_v3_sol_review.json"
    modal_report = project / "docs" / "07_stage4d_c_modal_bandwidth_audit_report_v3.md"
    scaling_report = project / "docs" / "07_stage4d_c_physical_scaling_audit_v3.md"
    b_accept = project / "docs" / "06_stage4d_b_sol_acceptance.md"
    manifest = project / "results" / "05_stage4c_scalability_tests" / "canonical_3slice_manifest_candidate.json"
    b_json = project / "results" / "06_stage4d_medium_run" / "stage4d_b_sol_acceptance.json"

    source_inventory = {
        "schema_version": "stage4e-a-source-inventory-1",
        "created_utc": now,
        "local_sources": [
            source_record(PDF, "local_Zotero_full_text_audit"),
            source_record(sol_review, "Sol_Stage4D-C-A-v3_scope"),
            source_record(sol_review_json, "Sol_Stage4D-C-A-v3_machine_decision"),
            source_record(modal_report, "Stage4D-C modal audit"),
            source_record(scaling_report, "Stage4D-C physical scaling audit"),
            source_record(b_accept, "Stage4D-B acceptance"),
            source_record(contract, "protocol_contract"),
            source_record(manifest, "frozen_3slice_manifest"),
            source_record(b_json, "Stage4D-B machine evidence"),
        ],
        "public_sources": [
            {
                "id": "vivdatashare_repo",
                "url": "https://github.com/xuepengfu/VIVdatashare",
                "kind": "public_GitHub_repository",
                "accessed_utc": now,
                "license_status": "no repository LICENSE file found; data README says availability is subject to negotiation",
            },
            {
                "id": "vivdatashare_experiment_csv",
                "url": "https://github.com/xuepengfu/VIVdatashare/blob/main/VIV_Experimental_Results/Bidirectionally_sheared_flow/DSF_S0T1_V048_1.csv",
                "raw_url": "https://raw.githubusercontent.com/xuepengfu/VIVdatashare/main/VIV_Experimental_Results/Bidirectionally_sheared_flow/DSF_S0T1_V048_1.csv",
                "kind": "public_raw_experiment_csv",
                "sha256": "507b6aadcda9437350c5035db384e7fbbbc0ebe708a6554df851c10498c743df",
                "bytes": 17142838,
            },
            {
                "id": "fu_2025_open_article",
                "url": "https://arxiv.org/abs/2502.05748",
                "doi": "10.1016/j.marstruc.2025.103895",
                "kind": "open_preprint_and_method_reference",
            },
            {
                "id": "chaplin_2005_ora",
                "url": "https://ora.ox.ac.uk/objects/uuid:d451bda3-8d21-4e16-b0e7-0e0593a603cf",
                "doi": "10.1016/j.jfluidstructs.2005.05.016",
                "kind": "public_repository_bibliographic_record",
            },
            {
                "id": "trim_2005",
                "url": "https://www.sciencedirect.com/science/article/pii/S0889974605001325",
                "doi": "10.1016/j.jfluidstructs.2005.07.014",
                "kind": "primary_experiment_article_record",
            },
            {
                "id": "song_2011",
                "url": "https://www.sciencedirect.com/science/article/pii/S0029801811001107",
                "doi": "10.1016/j.oceaneng.2011.05.020",
                "kind": "primary_experiment_article_record",
            },
        ],
        "identity_boundary": "Literature parameters and a public CSV are evidence inputs; they do not authorize a real CFD run or freeze a production benchmark.",
    }
    write_json("source_inventory.json", source_inventory)

    candidates = [
        {
            "id": "vivdatashare_bidirectional_shear_v048",
            "title": "SJTU bidirectionally sheared flexible-pipe VIV test, Umax=0.48 m/s",
            "source_type": "primary_experiment_with_public_selected_raw_data_and_processing_code",
            "source": "Fu et al. 2025; underlying bidirectional-shear experiment; VIVdatashare repository",
            "public_traceability": "CSV DSF_S0T1_V048_1.csv plus main1.m; raw file SHA-256 recorded in source_inventory",
            "parameters": {
                "L_m": 7.64, "D_m": 0.02841, "L_over_D": 268.9193945793735,
                "mass_per_length_kgpm": 1.24, "EI_Nm2": 58.6, "EA_N": 940000.0,
                "top_tension_N": 980.0, "Umax_mps": 0.48,
                "zeta_percent": 2.58, "sampling_Hz": 250.0,
                "rho_fluid_kgpm3": None, "nu_m2ps": None,
            },
            "data_products": ["raw strain channels", "raw force-sensor channels", "processing script", "modal reconstruction path"],
            "missing_or_uncertain": [
                "complete raw uniform and linearly-sheared cases are not in the public tree",
                "fluid density/viscosity and temperature are not specified in the audited CSV/script",
                "repository has no explicit license; README states data availability after negotiation",
                "force channels are sensor signals, not a validated distributed hydrodynamic-force field",
            ],
            "fit_to_current_three_slice": "medium: flexible-pipe physics and public raw channels fit, but bidirectional shear and Re~1.36e4 differ from the project's Re=80/100/120 same-direction slices",
            "score_10": 7.2,
        },
        {
            "id": "chaplin_huera_delft_delta_stepped_current",
            "title": "Chaplin et al. / F. J. Huera Huarte Delft Delta stepped-current tension riser",
            "source_type": "primary_experiment_published_parameters_secondary_local_thesis_audit",
            "source": "Chaplin et al. 2005; Huera Huarte 2006; local Duanmu dissertation Chapter 6",
            "public_traceability": "parameter tables and plotted response are public/repository-accessible; raw time-series licensing not established",
            "parameters": {
                "L_m": 13.12, "D_m": 0.028, "L_over_D": 468.57142857142856,
                "submerged_uniform_length_m": 5.94, "EI_Nm2": 29.88,
                "top_tension_N": 1610.0, "U_mps": 0.605, "mass_ratio_reported": 3.0,
                "Re_reported": 16940.0, "first_frequency_reported_Hz": 1.2237,
                "first_ten_frequencies_Hz": [1.2237,2.4516,3.6878,4.9364,6.2014,7.4867,8.7961,10.133,11.520,12.906],
            },
            "data_products": ["parameter table", "spanwise mean displacement", "CF/IL response plots", "hydrodynamic coefficient plots"],
            "missing_or_uncertain": [
                "raw displacement/strain/force time series not obtained in this audit",
                "mass per length, EA, damping and fluid properties are not all given in the audited table",
                "the frequency table's dry/wet state is not unambiguously labelled in the local thesis extraction",
            ],
            "fit_to_current_three_slice": "high for top-tensioned flexible-riser validation and stepped/nonuniform flow, but not directly reproducible without raw-data access and is far above the project's Re",
            "score_10": 7.8,
        },
        {
            "id": "trim_trondheim_high_mode_riser",
            "title": "Trim et al. 2005 Trondheim/NDP long marine-riser benchmark",
            "source_type": "primary_experiment_published_benchmark",
            "source": "Trim, Braaten, Lie & Tognarelli, Journal of Fluids and Structures 21(3), 335-361",
            "public_traceability": "article metadata and benchmark description public; raw series not located in the audit",
            "parameters": {
                "length_m": 38.0, "L_over_D_reported": 1400.0,
                "outer_inner_diameter_m": [0.027,0.024], "mass_per_length_kgpm": 0.76,
                "EI_Nm2": 37.2, "youngs_modulus_Pa": 2.1e11,
                "top_tension_N": 3700.0, "tow_speed_range_mps": [0.3,2.4],
                "expected_CF_modes": [2,14], "test_runs": 341,
            },
            "data_products": ["spanwise strain", "acceleration", "uniform and linearly-sheared responses", "strake comparison"],
            "missing_or_uncertain": ["raw time series and damping not found", "full fluid-property and calibration metadata not in the public audit record"],
            "fit_to_current_three_slice": "medium-low: excellent high-mode experiment but aspect ratio, Reynolds number and test topology differ materially",
            "score_10": 6.8,
        },
        {
            "id": "song_dalian_uniform_long_pipe",
            "title": "Song et al. 2011 Dalian uniform-flow long flexible riser",
            "source_type": "primary_experiment_published_benchmark",
            "source": "Song et al., Ocean Engineering 38(11-12), 1308-1322",
            "public_traceability": "article metadata and experimental setup public; raw series not located in the audit",
            "parameters": {
                "length_m": 28.04, "D_m": 0.016, "L_over_D": 1752.5,
                "wall_thickness_m": 0.0005, "tow_speed_range_mps": [0.18,0.60],
                "Re_range_reported": [3000,10000], "pretension_N": [600,700,800],
                "St_reported_approx": 0.18, "CF_modes_max": 6, "IL_modes_max": 12,
            },
            "data_products": ["FBG strain measurements CF/IL", "multi-mode uniform-flow response"],
            "missing_or_uncertain": ["mass/EI/EA/damping not complete in the audit record", "raw data not located", "horizontal towing differs from current vertical TTR"],
            "fit_to_current_three_slice": "medium: strong uniform-flow flexible-pipe experiment, weak direct match to vertical nonuniform slices",
            "score_10": 6.4,
        },
    ]
    write_json("benchmark_candidate_matrix.json", {
        "schema_version": "stage4e-a-candidate-matrix-1",
        "created_utc": now,
        "minimum_required_fields": ["L", "D", "mass_per_length", "EI", "EA", "top_tension", "U_or_profile", "data_traceability", "damping_or_explicit_missing"],
        "candidates": candidates,
        "selection_rule": "A candidate is not considered complete merely because a paper reports a parameter table; raw-data accessibility, license/permission and dry/wet identity are separate fields.",
    })

    write_json("vivdatashare_audit.json", {
        "schema_version": "stage4e-a-vivdatashare-audit-1",
        "repository": "https://github.com/xuepengfu/VIVdatashare",
        "observed_public_tree": {
            "experimental_results": ["Bidirectionally_sheared_flow/", "README.md"],
            "numerical_codes": ["Flexible_pipe/", "Bluff_pipe/", "README.md"],
            "license_file_found": False,
        },
        "readme_findings": [
            "The repository separates VIV_Experimental_Results and VIV_Numerical_Codes.",
            "The experiment README says the selected raw strain data are shared because of contract limitations and that full data availability is after negotiation.",
            "The numerical README describes an OpenFOAM-8, MATLAB 2018, 2D strip method based on an Euler beam with constant tension.",
        ],
        "raw_case": {
            "file": "DSF_S0T1_V048_1.csv",
            "sha256": "507b6aadcda9437350c5035db384e7fbbbc0ebe708a6554df851c10498c743df",
            "bytes": 17142838,
            "header_channels": ["RecordID", "TestID", "time/metadata column with encoding loss in raw export", "TF1_Fx/Fy/Fz", "TF2_Fx/Fy/Fz", "CF strain channels", "IL strain channels"],
            "processing": {"script": "main1.m", "sampling_Hz": 250.0, "dt_s": 0.004, "bandpass_Hz": [0.01,20.0], "CF_gage_count": 9, "IL_gage_count": 14, "uses_raw_unfiltered_for_this_case": True},
        },
        "reproducibility_status": "partially_reproducible_public_audit_only",
        "blocking_items_for_formal_primary": [
            "license/negotiation permission must be confirmed by Sol",
            "full fluid properties and calibration metadata must be obtained",
            "current three-slice same-direction flow is not the published bidirectional-shear case",
        ],
    })

    write_json("duanmu_method_audit.json", {
        "schema_version": "stage4e-a-duanmu-method-audit-1",
        "local_pdf": str(PDF),
        "pdf_sha256": sha256(PDF) if PDF.exists() else None,
        "document": "Duanmu Yu, Development of Computer Code for Vortex-Induced Vibration of Long Flexible Riser and Its Applications, SJTU dissertation, 2017",
        "audited_sections": ["Chapter 1 dimensionless definitions", "Chapter 6 standard flexible-riser validation", "Chapter 7 parameter studies"],
        "chapter6_parameter_table": {
            "D_m": 0.028, "L_m": 13.12, "L_over_D": 469.0, "submerged_uniform_length_m": 5.94,
            "EI_Nm2": 29.88, "top_tension_N": 1610.0, "U_mps": 0.605, "mass_ratio": 3.0, "Re": 16940.0,
        },
        "chapter6_frequency_table_Hz": [1.2237,2.4516,3.6878,4.9364,6.2014,7.4867,8.7961,10.133,11.520,12.906],
        "chapter6_numerical_setup": {"structure_nodes": 91, "structure_elements": 90, "CFD_strips": 20, "mesh_cases_cells": [46820,71653,98640], "selected_mesh": "Mesh I"},
        "chapter6_force_comparison": {"Mesh_I_Cd_mean": 1.136, "Mesh_I_Cl_rms": 0.851, "Mesh_I_St": 0.22, "MARIN_exp_Cd_mean": 1.16, "MARIN_exp_Cl_rms": 0.83, "MARIN_exp_St": 0.19},
        "method_audit": [
            "The thesis uses OpenFOAM/viv-FOAM-SJTU with a strip method and a conventional FEM beam, not ANCF.",
            "The validation experiment is a stepped-current Delft Delta setup shared historically with Chaplin et al.; this is a strong physical reference but not a license for raw-data redistribution.",
            "The extracted Table 6-2 frequency state is not unambiguously labelled dry or wet; it must not be merged with the present ANCF dry frequencies without an explicit interpretation.",
        ],
        "reuse_boundary": "method/parameter reference only; no production code or old evidence was modified",
    })

    primary = {
        "schema_version": "stage4e-a-selected-primary-1",
        "status": "candidate_recommended_not_frozen",
        "candidate_id": "vivdatashare_bidirectional_shear_v048",
        "why": ["public raw CSV and processing script exist", "full geometric, stiffness, tension, damping and sampling parameters are available from the article/repository audit", "supports a reproducible data-ingestion test before any CFD decision"],
        "not_a_formal_freeze": "Sol must confirm license/permission, fluid properties, dry/wet interpretation and whether a bidirectional-shear benchmark is physically appropriate for the current same-direction three-slice campaign.",
        "recommended_use": "offline data pipeline and parameter-reconstruction pilot; not immediate OpenFOAM entry",
    }
    fallback = {
        "schema_version": "stage4e-a-selected-fallback-1",
        "status": "fallback_candidate_not_frozen",
        "candidate_id": "chaplin_huera_delft_delta_stepped_current",
        "why": ["closest published top-tensioned flexible-riser and stepped/nonuniform-flow topology", "complete parameter table and frequency table were audited locally"],
        "blocking_items": ["raw time series and license not confirmed", "dry/wet frequency identity not explicit", "mass per length, EA and damping incomplete"],
    }
    write_json("selected_primary_benchmark.json", primary)
    write_json("selected_fallback_benchmark.json", fallback)

    rho_w = 1025.0
    project = {"L":10.0,"D":1.0,"mass_per_length":1171.421360699,"EI":3.4943984173e9,"EA":3.0889709766e10,"T":1e7}
    p0 = candidates[0]["parameters"]
    Dp, Lp, mp, EIp, EAp, Tp, Up = p0["D_m"], p0["L_m"], p0["mass_per_length_kgpm"], p0["EI_Nm2"], p0["EA_N"], p0["top_tension_N"], p0["Umax_mps"]
    A_disp_p = math.pi*Dp**2/4
    A_disp_c = math.pi*project["D"]**2/4
    flows = []
    bank_freq = [(0.8,0.10733640842189707),(1.0,0.14149994022481596),(1.2,0.17832790498556134)]
    for U,f in bank_freq:
        flows.append({"U_mps":U,"Re":U*project["D"]/0.01,"St_from_existing_bank":f*project["D"]/U,"f_s_Hz":f,"Ur_using_project_f1_Hz":U/(27.50934575579332*project["D"])})
    dimensionless = {
        "schema_version": "stage4e-a-dimensionless-mapping-1",
        "definitions": {"Re":"U D/nu","Ur":"U/(f_n D)","m_star":"m/(rho_f*pi*D^2/4)","Sc":"2*m_star*zeta","EI_star":"EI/(rho_f U^2 D^3)","EA_star":"EA/(rho_f U^2 D^2)","T_star":"T/(rho_f U^2 D^2)","St":"f_s D/U"},
        "public_candidate": {
            "L_over_D": Lp/Dp, "m_star_rho1000": mp/(1000*A_disp_p), "m_star_rho1025": mp/(1025*A_disp_p),
            "Re_at_Umax_if_nu_1e-6": Up*Dp/1e-6, "Sc_if_zeta_0p0258": 2*(mp/(1000*A_disp_p))*0.0258,
            "EI_star_at_Umax_rho1000": EIp/(1000*Up**2*Dp**3), "EA_star_at_Umax_rho1000": EAp/(1000*Up**2*Dp**2),
            "T_star_at_Umax_rho1000": Tp/(1000*Up**2*Dp**2), "fluid_nu_assumption": "1e-6 m2/s only for dimensional illustration, not a source value",
        },
        "frozen_project": {
            "L_over_D": project["L"]/project["D"], "m_star_rho1025": project["mass_per_length"]/(rho_w*A_disp_c),
            "EI_star_by_slice": [{"U_mps":U,"EI_star":project["EI"]/(rho_w*U**2*project["D"]**3),"EA_star":project["EA"]/(rho_w*U**2*project["D"]**2),"T_star":project["T"]/(rho_w*U**2*project["D"]**2)} for U,_ in bank_freq],
            "Re_by_slice_with_nu_0p01": [{"U_mps":U,"Re":U/0.01} for U,_ in bank_freq],
            "existing_developed_flow": flows,
            "damping": "Rayleigh alpha=beta=0; physical damping is not identified by Stage 4E-A",
        },
        "mapping_conclusion": "Exact dynamic similarity with the public high-Re benchmark is not achieved by the frozen project (L/D, Re, EI*, T*, Ur and damping differ). Priority is transparent parameter reconstruction and a separately labelled engineering benchmark, not retroactive retuning.",
        "priority_order": ["fluid topology and boundary condition", "mass ratio and wet frequency", "Ur/frequency placement", "damping/Scruton with source evidence", "EI/EA/T dimensionless groups", "Reynolds number if computationally feasible"],
    }
    write_json("dimensionless_parameter_mapping.json", dimensionless)

    configs = {c["id"]: c for c in raw["configurations"]}
    ancf_design = {
        "schema_version": "stage4e-a-ancf-design-1",
        "source_raw": str(RAW),
        "core": "read-only src/structure_ancf_matlab; vertical_ttr_case + ancf_initialize + ancf_constraints + ancf_internal_force_tangent",
        "public_candidate": {"id": "public_vivdatashare_bidirectional", "mass_ratio": configs["public_vivdatashare_bidirectional"]["mass_ratio_no_added_mass"], "dry_modes_nElem4_Hz": configs["public_vivdatashare_bidirectional"]["results"][1]["dry_frequency_Hz"][:6], "static_max_abs_displacement_m": configs["public_vivdatashare_bidirectional"]["results"][1]["static_max_abs_displacement_m"]},
        "frozen_project": {"id": "frozen_project_vertical_ttr", "mass_ratio": configs["frozen_project_vertical_ttr"]["mass_ratio_no_added_mass"], "dry_modes_nElem2_Hz": configs["frozen_project_vertical_ttr"]["results"][0]["dry_frequency_Hz"][:6], "dry_modes_nElem4_Hz": configs["frozen_project_vertical_ttr"]["results"][1]["dry_frequency_Hz"][:6], "static_max_abs_displacement_m": configs["frozen_project_vertical_ttr"]["results"][1]["static_max_abs_displacement_m"]},
        "nElem_design_space": [{"nElem":n,"nNode":n+1,"ndof":6*(n+1)} for n in [2,4,8,16]],
        "design_rule": "Do not compare q vectors with different dimensions directly; compare frequencies and common-span mode shapes, and compare slice-center kinematics through H interpolation.",
        "vertical_core_limit": "The existing ANCF case is vertical and includes gravity/buoyancy; the horizontal towing benchmark is used as a parameter/modal diagnostic, not as a claim of geometry-equivalent FSI.",
        "wet_frequency_rule": "Use the dry ANCF result as the structural reference and report Ca=0.5/1.0/1.5 added-mass estimates separately; no experimental wet frequency is substituted.",
    }
    write_json("ancf_structural_design.json", ancf_design)

    mesh = {
        "schema_version": "stage4e-a-ancf-mesh-convergence-1",
        "source_raw": str(RAW),
        "criteria": {"adjacent_all_mode_frequency_relative_error": "<=0.01 target", "major_mode_frequency_relative_error": "<=0.02 target", "major_mode_MAC": ">=0.99 target"},
        "configurations": [],
    }
    for c in raw["configurations"]:
        pairs = c["mesh_convergence"]["adjacent_pairs"]
        mesh["configurations"].append({
            "id": c["id"],
            "nElem_results": [{"nElem":r["nElem"],"nNode":r["nNode"],"dry_frequency_Hz":r["dry_frequency_Hz"][:8],"static_max_abs_displacement_m":r["static_max_abs_displacement_m"],"static_newton_iterations":r["static_newton_iterations"],"static_residual":r["static_residual"]} for r in c["results"]],
            "adjacent_pairs": [{"coarse_nElem":p["coarse_nElem"],"fine_nElem":p["fine_nElem"],"frequency_max_relative_error":p["frequency_max_relative_error"],"frequency_first_mode_relative_error":p["frequency_first_mode_relative_error"],"major_modes_pass_2pct":p["major_modes_pass_2pct"],"mac_major_min":p["mac_major_min"],"mac_pass_0p99":p["mac_pass_0p99"],"all_mode_1pct_pass":p["frequency_pass_1pct"]} for p in pairs],
            "formal_4_vs_8_major_band_pass": bool(pairs[1]["major_modes_pass_2pct"] and pairs[1]["mac_pass_0p99"]),
            "formal_4_vs_8_all_mode_1pct_pass": bool(pairs[1]["frequency_pass_1pct"]),
        })
    mesh["conclusion"] = "The first three/major modes converge strongly for 4 versus 8 elements, but the strict all-mode <=1% target is not met for the retained modal set at 4 versus 8; no final production nElem is frozen by Luna."
    write_json("ancf_mesh_convergence.json", mesh)

    write_json("cost_estimate.json", {
        "schema_version": "stage4e-a-cost-estimate-1",
        "basis": {"stage4d_b_formal100_wall_s": 720.2629127,"mean_global_step_wall_s":7.202629127,"baseline_steps":100,"baseline_slices":3,"baseline_executions":300,"baseline_storage_bytes":577061011,"process_limit":2},
        "scenarios_for_1s_physical_time": [
            {"label":"minimum","slices":3,"dt_s":0.0025,"steps":400,"openfoam_executions":1200,"waves_per_global_step":2,"estimated_wall_h":0.80,"estimated_storage_GB":2.31,"status":"engineering_minimum; still no public-benchmark physical freeze"},
            {"label":"recommended","slices":5,"dt_s":0.00125,"steps":800,"openfoam_executions":4000,"waves_per_global_step":3,"estimated_wall_h":2.67,"estimated_storage_GB":7.69,"status":"requires five independent developed-flow sources/cases; not authorized in this task"},
            {"label":"high_risk","slices":8,"dt_s":0.00125,"steps":800,"openfoam_executions":6400,"waves_per_global_step":4,"estimated_wall_h":3.20,"estimated_storage_GB":12.30,"status":"requires eight independently developed flow sources/cases; high disk and validation risk"},
        ],
        "scaling_note": "Wall/storage estimates are linear projections from the measured Stage 4D-B run and assume identical mesh/IO behavior; they are not a performance guarantee.",
        "storage_policy": "No existing historical results were deleted or modified.",
    })

    summary = {
        "schema_version": "stage4e-a-candidate-summary-1",
        "status": "partially_completed",
        "scope": ["public literature/repository survey", "VIVdatashare raw/code audit", "Duanmu dissertation method/parameter audit", "dimensionless mapping", "offline ANCF static/modal and mesh audit", "cost projection"],
        "real_cfd_started": False,
        "primary_candidate": primary["candidate_id"],
        "fallback_candidate": fallback["candidate_id"],
        "primary_frozen": False,
        "strict_mesh_all_mode_gate": "not_passed_at_4_vs_8",
        "major_mode_mesh_diagnostic": "passed_for_first_three_modes_at_4_vs_8_for_both_audited_configurations",
        "main_blockers": ["public-data license/negotiation and complete metadata not confirmed", "public primary topology is bidirectional shear while the current campaign is same-direction nonuniform flow", "strict all-retained-mode <=1% frequency criterion is not met at 4 vs 8 elements"],
        "sol_decision_required": ["freeze primary or fallback benchmark", "confirm damping/added-mass/wet-frequency treatment", "authorize any later real CFD benchmark campaign"],
        "generated_utc": now,
    }
    write_json("stage4e_a_candidate_summary.json", summary)


if __name__ == "__main__":
    main()
